// 'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { motion } from "framer-motion";
import Navbar from "./components/Projects";
import Skills from "./components/Skills";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  // descriptionٍ: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <div className="main flex self-center justify-center ">
          
        {/* <motion.div 
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ ease: "easeInOut", duration: 1.00 }}
        className="flex flex-col  w-1/2 mt-48 justify-gap-10"
        > */}
          <Navbar/>
        {children}
        {/* </motion.div> */}
        <Skills/>
        </div>
        
      </body>
    </html>
  );
}
